### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by weltonwe** [jrishabh55/whmcs-verifyemail#1]
Activar module error hooks.php user

**Comment by weltonwe** [comment]
Error 
    use HSR\Hooks;
    Hooks::init()->addHooks([
        'ClientAdd',
        'ClientLogin',
    ]);
}

**Comment by jrishabh55** [comment]
Can you please give me the error you are reeving so that i can check it for you.

**Comment by weltonwe** [comment]
Oops!
Something went wrong and we couldn't process your request.
Please go back to the previous page and try again.

ParseError: syntax error, unexpected 'use' (T_USE) in /home/admin/web/user.xxxxx/public_html/modules/addons/hsrverifyemail/hooks.php:27
Stack trace:
#0 /home/admin/web/user.xxxxxx/public_html/includes/functions.php(0): unknown()
#1 /home/admin/web/user.xxxxx/public_html/init.php(0): load_hooks()
#2 /home/admin/web/user.xxxxxxx/public_html/xxxxxxx/clientsservices.php(0): unknown()
#3 {main}

**Comment by jrishabh55** [comment]
I have updated the file. Please test it now and let me know if this resolved your issue.

**Comment by weltonwe** [comment]
No error appears but is not working in whmcs 7.2.2

**Comment by jrishabh55** [comment]
Hi, I'm very sorry for the delay. i didn't get the time to reach out to this. I'll fix this within couple of days.

**Comment by jrishabh55** [comment]
I have rewrote the program and should work fine now. Please check and let me know
